<rule-set name="cheese rules"
		  xmlns="http://drools.org/rules"
          xmlns:java="http://drools.org/semantics/java">


    <rule name="Bob Likes Cheese">
        <parameter identifier="bob">
            <java:class>kobold.common.data.WorkflowMessage</java:class>
        </parameter>
        <java:condition>1 == 1</java:condition>
        <java:consequence>
            System.out.println( "Bob likes cheese." );
        </java:consequence>
    </rule>

</rule-set>
