<rules xmlns="http://drools.org/rules" xmlns:java="http://drools.org/semantics/java"> 
<semantics module="org.drools.semantics.java"/> 


<rule-set 	name="Kobold">

	<rule name="Client's Action">
		<parameter identifier="workflowMessage">
			<java:class xmlns:java="http://drools.org/semantics/java"> type="kobold.common.data.WorkflowMessage"</java:class>
		</parameter>
			<java:consequence xmlns:java="http://drools.org/semantics/java">
				workflowMessage.setMessageText("Erfolg!");
				modifyObject(workflowMessage);
			</java:consequence>
	</rule>
</rule-set>
